name: ClinicEngine CI/CD

on: 
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
  
  permissions:
    id-token: write
    contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Restore Backend Dependencies
        working-directory: ./ClinicEngine.API
        run: dotnet restore 
      
      - name: Build Backend
        working-directory: ./ClinicEngine.API
        run: dotnet build -c release --no-restore

      - name: Restore Test Dependencies
        working-directory: ./ClinicEngine.Tests
        run: dotnet restore

      - name: Run Backend Tests
        working-directory: ./ClinicEngine.Tests
        run: dotnet test --configuration Release --no-restore
        
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: install frontend dependencies
        working-directory: ./clinicengine-web
        run: npm ci 
      
      - name: build frontend
        working-directory: ./clinicengine-web
        run: npm run build
      
      - name: Configure AWS credentials
        if: github.event_name = 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }} 
          aws-region: us-east-1

      - name: Deploy frontend to S3
        if: github.event_name = 'push' && github.ref == 'refs/heads/main'
        working-directory: ./clinicengine-web
        run: aws s3 sync dist/ s3://clinicengine-web --delete

       
